# Generated by Django 5.1.3 on 2025-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ordermodel_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='tg_id',
            field=models.BigIntegerField(default=1, verbose_name='tg_id'),
        ),
    ]
